### ISSUE TITLE
Make redis database configurable

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-redis#4]
Add documentation and/or default config values that make it easy to specify which redis database to use.

**Comment by mattcollier** [comment]
@digitalbazaar/dev after looking at our options here, I'm inclined toward making use of the `prefix` client option here instead of separate database on the following grounds:

1. It's an easily understandable config options, using config option is synchronous.  I think a random N character prefix is more resilient to collisions than integer database values.
2. using database involves doing an async `client.select` command.  By default, redis only support 16 databases, whereas prefixes would be unlimited.
3. for whatever reason the redis documentation attempts to steer people away from using databases for separate applications.  https://redis.io/commands/select
4. bedrock-redis is designed to make it easy to initialize additional clients synchronously which we can still do with the config option, but not with the database/select option.

https://github.com/NodeRedis/node_redis#rediscreateclient

So, my intention is to add the `prefix` option to the config defaulted to null with a comment about the usefulness.  Then we just need to start using it in places so that everyone knows it's a thing.

Any objections?

**Comment by davidlehn** [comment]
Seems ok to me. Probably add some brief comments/docs about how and when to use that option and tradeoffs vs another redis server. I'm guessing short ids would be preferred here over something like a uuid?
